version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amaterasu
      POSTGRES_PASSWORD: idontknow
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
